config/routes.rb
MastercardMasterpassSampleApplication::Application.routes.draw do
  resources :donations

  resources :charities

  root "charities#index"

  get "master_pass" => "master_pass#index"
  get "donations/:handle/new" => "donations#new"
  post "donations/:handle/pay" => "donations#pay"
  post "donations/:handle/cc" => "donations#cc"

  post "oauth" => 'master_pass#oauth'
  post "oauthshoppingcart" => 'master_pass#oauthshoppingcart'

  get "oauthcallback" => 'donations#oauthcallback'
  # get "oauthcallback" => 'master_pass#oauthcallback'

  post "oauthcheckout" => 'master_pass#oauthcheckout'
  post "accesstoken" => 'master_pass#accesstoken'
  post "pairingtoken" => 'master_pass#pairingtoken'
  post "merchantinitialization" => 'master_pass#merchantinitialization'
  post "pairingconfiguration" => 'master_pass#pairingconfiguration'
  get "pairingcallback" => 'master_pass#pairingcallback'
  post "precheckout" => 'master_pass#precheckout'
  post "oauthpostback" => 'master_pass#oauthpostback'
  post "expresscheckout" => 'master_pass#expresscheckout'
  get "expresscheckout" => 'master_pass#expresscheckout'
  post "cart" => 'master_pass#cart'
  get "cartcallback" => 'master_pass#cartcallback'
  post "cartpostback" => 'master_pass#cartpostback'
end

app/models/charity.rb
class Charity < ActiveRecord::Base
  has_many :donations

  #TODO: add an index on handle
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  before_action :set_charity, only: [:edit, :update, :destroy]

  # GET /charities
  # GET /charities.json
  def index
    @charities = Charity.all
    @body_class = "home"
  end

  # GET /charities/1
  # GET /charities/1.json
  def show
    @charity = Charity.includes(:donations).find_by_handle(params[:id])
    @total_raised = @charity.donations.map {|d| d.amount}.reduce(:+).to_i

    if @charity.nil?
      redirect_to charities_url
    end
  end

  # GET /charities/new
  def new
    @charity = Charity.new
  end

  # GET /charities/1/edit
  def edit
  end

  # POST /charities
  # POST /charities.json
  def create
    @charity = Charity.new(charity_params)

    respond_to do |format|
      if @charity.save
        format.html { redirect_to @charity, notice: 'Charity was successfully created.' }
        format.json { render action: 'show', status: :created, location: @charity }
      else
        format.html { render action: 'new' }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charities/1
  # PATCH/PUT /charities/1.json
  def update
    respond_to do |format|
      if @charity.update(charity_params)
        format.html { redirect_to @charity, notice: 'Charity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charities/1
  # DELETE /charities/1.json
  def destroy
    @charity.destroy
    respond_to do |format|
      format.html { redirect_to charities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charity
      @charity = Charity.includes(:donations).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charity_params
      params.require(:charity).permit(:name, :handle)
    end
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/views/charities/_form.html.erb
<%= form_for(@charity) do |f| %>
  <% if @charity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charity.errors.count, "error") %> prohibited this charity from being saved:</h2>

      <ul>
      <% @charity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :handle %><br>
    <%= f.text_field :handle %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charities/edit.html.erb
<h1>Editing charity</h1>

<%= render 'form' %>

<%= link_to 'Show', @charity %> |
<%= link_to 'Back', charities_path %>

app/views/charities/index.html.erb
<div class="logoContainer" style="padding-top:65px">
  <img src="/images/piccoloLogo.png" height="75"></img>
  <p style="padding-top:30px" class="lead">Simple micro-donations</p>
</div>

<div class="container">
  <div class="demo-row">
    <div class="demo-title"></div>

    <div class="demo-col home-page-search">
      <div class="form-group">
        <form id="search" action="/charities/">
          <input class="form-control input-hg" type="text" id="charity-search" placeholder="Search for projects..." />
          <input type="submit" style="display:none">
        </form>
      </div>
    </div>

    <!-- <div class="demo-col background-white">
      <ul class="nav nav-list">
        <li class="nav-header">Latest Donations</li>
        <li>
          <a href="#fakelink">
            UX Design
            <span class="badge pull-right">19</span>
          </a>
        </li>
        <li>
          <a href="#fakelink">
            Photography
            <span class="badge pull-right">130</span>
          </a>
        </li>
        <li>
          <a href="#fakelink">
            Art
            <span class="badge pull-right">9</span>
          </a>
        </li>
        <li class="divider"></li>
        <li class="nav-header">Top Projects</li>
        <li>
          <a href="#fakelink">
            Brand new
            <span class="badge pull-right">69</span>
          </a>
        </li>
        <li>
          <a href="#fakelink">
            Read-used
            <span class="badge pull-right">21</span>
          </a>
        </li>
        <li>
          <a href="#fakelink">
            Work-used
            <span class="badge pull-right">40</span>
          </a>
        </li>
      </ul>
    </div> -->
  </div>
</div>

<div class="mtl pbl">
      <div class="bottom-menu">
        <div class="container">
          <div class="row">
            <div class="col-md-2 col-sm-2">
              <a href="/" class="bottom-menu-brand">Piccolo</a>
            </div>
            <div class="col-md-8 col-sm-8">
              <ul class="bottom-menu-list">
                <li><a href="#fakelink">Charities</a></li>
                <li><a href="#fakelink">How it works</a></li>
                <li><a href="#fakelink">About</a></li>
                <li><a href="#fakelink">Privacy</a></li>
                <li><a href="#fakelink">Terms</a></li>
              </ul>
            </div>
            <div class="col-md-2 col-sm-2">
              <ul class="bottom-menu-iconic-list">
                <li><a href="#fakelink" class="fui-pinterest"></a></li>
                <li><a href="#fakelink" class="fui-facebook"></a></li>
                <li><a href="#fakelink" class="fui-twitter"></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div> <!-- /bottom-menu-inverse -->
    </div>

<!--
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Handle</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @charities.each do |charity| %>
      <tr>
        <td><%= charity.name %></td>
        <td><%= charity.handle %></td>
        <td><%= link_to 'Show', charity %></td>
        <td><%= link_to 'Edit', edit_charity_path(charity) %></td>
        <td><%= link_to 'Destroy', charity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

<!-- <%= link_to 'New Charity', new_charity_path %> -->

app/views/charities/new.html.erb
<h1>New charity</h1>

<%= render 'form' %>

<%= link_to 'Back', charities_path %>

app/views/charities/show.html.erb
<div class="d container" style="margin-bottom:20px">


	<div class="input-group input-group-hg">
		<span class="input-group-addon">@</span>
		<input class="form-control" id="prependedInput-01" type="text" placeholder="twitter" value="<%= @charity.handle %>">
	</div>

	<table width="100%">
		<tr>
			<td style="text-align:center">
				<div class='total-amount-raised'>
					<p>$<%= @total_raised %></p>
				</div>
			</td>
		</tr>
	</table>
	<p class="total-amount-raised-copy" style="margin-bottom:10px">Total raised</p>
	<%= link_to 'Give', '/donations/' + @charity.handle + '/new', id: @charity.id, class: 'btn btn-hg btn-primary btn-block' %>
</div>

<div class="container donation-list-container">
	<ul class="latest-donations-container">
		<% @charity.donations.each do |d| %>
			<li class="latest-donations">
				<!-- <img src="../images/xbox.jpg" alt=""></img> -->
				<div class="donation-amount">
					<p>$<%= d.amount.to_i %></p>
				</div>
				<div class="comment-container">
					<p class="name"><%= d.name %></p>
					<p class="message"><%= d.comment %></p>
				</div>
			</li>
		<% end %>
	</ul>
</div>

<!-- <div class="back-container"> -->
	<!-- <%= link_to 'Back', charities_path %> -->
<!-- </div> -->
<!-- <%= link_to 'Edit', edit_charity_path(@charity) %> -->